all:
  children:
    proxmox:
      hosts:
        prox2:
          ansible_host: 192.168.0.205
          ansible_user: root
          ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') + '/.ssh/id_ed25519' }}"
    k3s:
      hosts:
        k3s-node01:
          ansible_host: 192.168.0.221
        k3s-node02:
          ansible_host: 192.168.0.222
        k3s-node03:
          ansible_host: 192.168.0.223
        k3s-node04:
          ansible_host: 192.168.0.224
        k3s-node05:
          ansible_host: 192.168.0.225
        k3s-node06:
          ansible_host: 192.168.0.226
